apiVersion: v1
kind: Service
metadata:
  name: back-service
  labels:
    app: app-back
spec:
  type: ClusterIP
  selector:
    app: app-back
  ports:
    - name: http
      port: 8080
      targetPort: 8080
