apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: app-front
spec:
  type: NodePort
  selector:
    app: app-front
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
